### ISSUE TITLE
Avoid confusion with Promises

### ISSUE THREAD

**Issue by gaearon** [redux-effects/declarative-promise#1]
I think it's important to rename `then()` to something else. There was a lot of pain involved in establishing Promises A+ and [implementations that chose to name their non-Promise thing `then()` made everyone unhappy](https://gist.github.com/domenic/3889970).

**Comment by ashaffer** [comment]
I'm not opposed to that idea.  I mostly named it that way so that it would be familiar to people

Some alternatives I can think of are `when` and `bind` (i.e. haskell's term - though this is overloaded in JS as well unfortunately).

Do you have any ideas/preference?

**Comment by gaearon** [comment]
> I mostly named it that way so that it would be familiar to people

That's the problem: something that is familiar but acts unfamiliar is going to cause trouble, just like it did in jQuery's unfortunate case. I'd probably call it `.attach()` or `.step()`. It's mutative right?

**Comment by ashaffer** [comment]
Yes it is mutative.  `.step()` seems ok to me, i'll change it to that.
